[package]
name = "fungible_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr ="0x404d6ea687601feece8f2705fc5453c3634219bbd18b53ddb253b561ae62c53a"
initial_creator_addr ="0x404d6ea687601feece8f2705fc5453c3634219bbd18b53ddb253b561ae62c53a"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
